### ISSUE TITLE
Meet error with 429

### ISSUE THREAD

**Issue by Destore2023** [filecoin-station/spark#100]
Hello spark team,

Client's sps met some problem about retrieval.  

>@Destore2023 Hello allocator, these sps support retrieval actually. But they said that they met some error message about spark. announce message to https://cid.contact/ingest/announce: 429 Too Many Requests: Too Many Requests

The error---announce message to https://cid.contact/ingest/announce: 429 Too Many Requests: Too Many Requests

They don't know what to do. Please help solve this problem. Thank you!

**Comment by juliangruber** [comment]
This error is about announcing the retrieval to IPNI (cid.contact), not Spark itself. I have asked about this error in Filecoin Slack: https://filecoinproject.slack.com/archives/C02T827T9N0/p1730721573732309

**Comment by juliangruber** [comment]
See https://filecoinproject.slack.com/archives/C03CKDLEWG1/p1728719842581229?thread_ts=1728713220.074939&channel=C03CKDLEWG1&message_ts=1728719842.581229:

> Announcements are rate limited to 1 per second by cid.contanct. Also announcements are idempotent and delay tolerant: as long as one gets to cid.contact it will discover all unseen ads.
The cause is that the provider is making too many announcements too fast. You can ignore these responses as far as advertisement ingestion goes.
